name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
    - name: create artifact
      run: |
        tar cvf blog.tar _site/*
    - name: upload
      run: |
        ls -la
        curl -X PUT --data-binary '@blog.tar' ${{ secrets.OCI_BUCKET_UPLOAD }}/blog/blog.tar
